-- Course Database Systems - PPU - Dr. Mahmoud Al-Saheb
-- BY:A7mad_Joba
-- Environment: Oracle Live SQL

CREATE TABLE DEPT (
  DEPTNO NUMBER(2),
  DNAME VARCHAR2(14),
  LOC VARCHAR2(13),
  CONSTRAINT dept_pk PRIMARY KEY (DEPTNO)
);


CREATE TABLE EMP (
  EMPNO NUMBER(4),
  ENAME VARCHAR2(10),
  JOB VARCHAR2(9),
  MGR NUMBER(4),
  HIREDATE DATE,
  SAL NUMBER(7,2),
  COMM NUMBER(7,2),
  DEPTNO NUMBER(2),
  CONSTRAINT emp_pk PRIMARY KEY (EMPNO),
  CONSTRAINT emp_dept_fk FOREIGN KEY (DEPTNO) REFERENCES DEPT(DEPTNO)
);
