-- Course Database Systems - PPU - Dr. Mahmoud Al-Saheb
-- BY:A7mad_Joba
-- Environment: Oracle Live SQL


SELECT DEPTNO, COUNT(*) AS NUM_EMP
FROM EMP
GROUP BY DEPTNO;


SELECT JOB, AVG(SAL) AS AVG_SAL
FROM EMP
GROUP BY JOB;


SELECT DEPTNO, SUM(SAL) AS TOTAL_SAL
FROM EMP
GROUP BY DEPTNO;


SELECT MGR, COUNT(*) AS TEAM
FROM EMP
GROUP BY MGR;


SELECT DEPTNO, COUNT(*) AS NUM_EMP
FROM EMP
GROUP BY DEPTNO
HAVING COUNT(*) > 2;


SELECT JOB, AVG(SAL) AS AVG_SAL
FROM EMP
GROUP BY JOB
HAVING AVG(SAL) > 2000;