-- Course Database Systems - PPU - Dr. Mahmoud Al-Saheb
-- BY:A7mad_Joba
-- Environment: Oracle Live SQL

INSERT INTO DEPT (DEPTNO, DNAME, LOC) 
VALUES (1, 'ACCOUNTING', 'Hebron');
INSERT INTO DEPT (DEPTNO, DNAME, LOC) 
VALUES (2, 'RESEARCH',   'Ramallah');
INSERT INTO DEPT (DEPTNO, DNAME, LOC) 
VALUES (3, 'SALES',      'Gaza');
INSERT INTO DEPT (DEPTNO, DNAME, LOC) 
VALUES (4, 'OPERATIONS', 'Hebron');

INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (1000, 'Ahmad', 'CLERK', NULL, TO_DATE('01-01-2020', 'DD-MM-YYYY'), 800, NULL, 1);

INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (1001, 'Aziz', 'SALESMAN', 1003, TO_DATE('02-01-2020', 'DD-MM-YYYY'), 1800, 200, 2);

INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (1002, 'Obada', 'ANALYST', 1004, TO_DATE('03-01-2020', 'DD-MM-YYYY'), 2500, NULL, 2);

INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (1003, 'Yaseen', 'MANAGER', NULL, TO_DATE('04-01-2020', 'DD-MM-YYYY'), 3000, NULL, 1);

INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES (1004, 'Mohammad', 'MANAGER', 1003, TO_DATE('05-01-2020', 'DD-MM-YYYY'), 3000, NULL, 3);




