-- Course Database Systems - PPU - Dr. Mahmoud Al-Saheb
-- BY:A7mad_Joba
-- Environment: Oracle Live SQL

--JOINS

SELECT EMP.ENAME, DEPT.DNAME
FROM EMP JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO;

SELECT E.ENAME AS EMPLOYEE, M.ENAME AS MANAGER
FROM EMP E LEFT JOIN EMP M ON E.MGR = M.EMPNO;

SELECT E.ENAME, D.DNAME
FROM EMP E FULL OUTER JOIN DEPT D ON E.DEPTNO = D.DEPTNO;